// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZlxJDMNLOW0V50j1kK3bR0R4PL9Is9-8',
    appId: '1:438453356510:web:a188b1caa8978533edbf4f',
    messagingSenderId: '438453356510',
    projectId: 'signinauth-d0a3c',
    authDomain: 'signinauth-d0a3c.firebaseapp.com',
    storageBucket: 'signinauth-d0a3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ptbxpGJ3va_xNoSY2mKW2qxg6c66wp0',
    appId: '1:438453356510:android:4147d3b0f7006905edbf4f',
    messagingSenderId: '438453356510',
    projectId: 'signinauth-d0a3c',
    storageBucket: 'signinauth-d0a3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNVeF2ob0LBqBSNIbmq1G20O1en2N3IEM',
    appId: '1:438453356510:ios:d67a956b344c8a43edbf4f',
    messagingSenderId: '438453356510',
    projectId: 'signinauth-d0a3c',
    storageBucket: 'signinauth-d0a3c.appspot.com',
    iosBundleId: 'com.example.flutterGoogleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNVeF2ob0LBqBSNIbmq1G20O1en2N3IEM',
    appId: '1:438453356510:ios:7a3c51a4c0e4bc3eedbf4f',
    messagingSenderId: '438453356510',
    projectId: 'signinauth-d0a3c',
    storageBucket: 'signinauth-d0a3c.appspot.com',
    iosBundleId: 'com.example.flutterGoogleSignin.RunnerTests',
  );
}
